// Simple client-side config for marketing/contact knobs
export const SITE_NAME = 'Clayshan';
// E.164 (no +, country code first). Example: 91xxxxxxxxxx for India
export const WHATSAPP_NUMBER = '919140210648';
// Default message if we cannot access window/document (SSR)
export const WHATSAPP_DEFAULT_MESSAGE = `Hello! I would like to know more about ${SITE_NAME}.`;

// Optional: Brand logo URL used in the navbar and social previews.
// You can set this to an absolute URL (e.g., a Supabase public URL) or a local asset under /public.
// Use the wordmark (logo with the brand name). For very small screens the CSS
// scales it down automatically. If you prefer the monogram on mobile, we can
// swap it via a small media-query or runtime breakpoint.
export const LOGO_URL: string = '/assets/brand/clayshan-logo.svg';
export const LOGO_MONOGRAM_URL: string = '/assets/brand/clayshan-mark.svg';
export const LOGO_GLYPH_URL: string = '/assets/brand/clayshan-glyph.svg';

// Social/OpenGraph image (1200x630 recommended). Default to local SVG
// (you can export PNG/WebP via scripts/export-brand.mjs and update this).
export const OG_IMAGE_URL: string = '/assets/brand/clayshan-og-1200x630.svg';

// PWA / Icon paths (generated by scripts/export-brand.mjs)
export const ICON_192: string = '/assets/brand/clayshan-mark-192.png';
export const ICON_512: string = '/assets/brand/clayshan-mark-512.png';
export const FAVICON_32: string = '/assets/brand/favicon-32.png';
export const THEME_COLOR: string = '#d4af37';

// UX knobs
export const FREE_SHIPPING_THRESHOLD_INR = 4999; // show progress until unlocked
export const ORDER_CUTOFF_HOUR_LOCAL = 16; // 4 PM local time for same-day dispatch
